version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - Berkmann18
  labels:
  - dependencies
  - "Priority: Low"
